commonLabels:
  app.kubernetes.io/instance: "{{ app_name }}"

# do not forget to update the patch with the namespace
namespace: rook-ceph

resources:
  - ceph-priority.yaml
  - apisixroute.yaml

helmCharts:
- name: rook-ceph-cluster
  repo: https://charts.rook.io/release
  version: v1.7.7
  valuesFile: values.yaml
  namespace: rook-ceph

patches:
  - path: patch.yaml
    target:
      group: ceph.rook.io
      version: v1
      kind: CephCluster
      name: rook-ceph
